### ISSUE TITLE
Stop Getting Random results

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#42]
If the user has clicked the search button, stop running random query on move. If user clicks 'Reset' reactivate random query when moving.
This is because I, and assume others, want to query something specific, and then scrutinise the results and the places and where they are by zooming in and out etc. I don't want my specific results to suddenly get mixed up with random stuff. I do this a lot when I am looking for a place name and Google only finds one and I know it's the wrong one. GHAP shows me all the place names so I can check for the ones in the region I'm looking at and then zoom in and out to check the landforms are relevant to what I'm studying. I can't do this if the random search suddenly adds lots of places when I move.
The assumption will be that if the user has searched for something specific, they only want to see that and stop getting random results.

**Comment by MufengNiu** [comment]
Hi @BillPascoe 

There might be some misunderstanding about the current search behavior , it works as such:

- When a user initiates a search, clear all current points on the map.
- Retrieve 200 random places from the total search results, restricted location to the current viewing bounding box. (We decided not to return all points due to potential timeout issues in previous implementations.)
- If the user starts dragging or zooming during the search, retrieve another 200 places from the total search results within the updated bounding box and add them to the map.
- Search will be turned off when reset

Let me know if you want to change the features

**Comment by MufengNiu** [comment]
No change for this one right now
