### ISSUE TITLE
Add New Layer Workflow

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#47]
When I click to add a place to the map, and I want to add a new layer, it takes me to a new layer form, and doesn't return me where I was. I need to start over. This is a confusing workflow and will lose a new user. The new layer option should give me a text box, either made visible in the form, or another small pop up, with the label 'New Layer Name'. It should have text next to it or a help icon with text saying "You can edit information about this layer later under 'My Layers'."
This should add the new layer name to the drop down box so it can be selected immediately without having to go away and come back. The new layer should be added when user adds the place, and then the place is added to it.

**Comment by IanMcCrabb** [comment]
@isobel-andrews might get you to wire-frame this for mufeng

**Comment by isobel-andrews** [comment]
[TLCMap 'New layer'.pdf](https://github.com/user-attachments/files/17201110/TLCMap.New.layer.pdf)

Wireframe attached. Instead of doing a new popup I think it's cleaner to 'slide' the forms across within the same popup. @MufengNiu hopefully this makes sense in the wireframes. Please let me know if you're confused.

**Comment by BillPascoe** [comment]
One glitch:

If I am a completely new user and add a new place but don't click the 'new layer' button, and accept the default 'Bill's Places' layer, there is a glitch. If I am a new user and create a new layer is does work. 
Details: Using the admin interface I deleted my other test account, and then logged out and created a new test account. I didn't confirm account by email as that is not possible with test. I just went back to the home page and right clicked on the map to add a new layer. I did not click 'New Layer' but left it as the default 'Bill's Places'. When I finished it zoomed to the place, but did not show the dot on the map. I tried all this again, but added a new layer, and it zoomed to the place and did show the dot correctly.

Some minor UI changes:

On the 'Add a Place' window, next to the 'Layer*' label add a question mark icon tip that says "A place must be part of a 'Layer'. A Layer might be places about a certain topic, or simply 'My Places'. You must create a Layer to add places to it. You can change Layer details later after you create it. You will return to this screen after creating a new layer."

Move the layer 'Description' field to the top of the window under 'Layer Name' because these are the only required fields.

On the 'New Layer' window make the asterisks red (same as the 'Add a place' pop up).

**Comment by IanMcCrabb** [comment]
@MufengNiu if you can action these changes (the bug and the UI changes that Bil mentions) then please do so.  We can then go lievWednesday

**Comment by MufengNiu** [comment]
If a new user accept the 'xxx's first Places' layer, the layer created will be private by default. Thats why the place is not shown on the map. I have turned off the zoom to new place function if the new place is being added to a private layer

**Comment by MufengNiu** [comment]
The layer created for user ' xxx's first layer' have be set to public

**Comment by BillPascoe** [comment]
Ok, it's good.
